name: JonathanSaiz
favicon: null
layout_spectrum: 0.523789691971615
typography_spectrum: 0.18838308402337134
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.22650690842419863
  lightness: 0.9137909195851535
  saturation: 0.708375059068203
  rhythmicContrast: 0.37330994033254683
purpose: []
